---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress@sha256:2a26ea68ed69ccb3c627761626ff240c2faa28fcd103ed53b026fd5a0d027e42

          ports:
            - containerPort: 80
